Add Javascript SDK Page
lukasjhan/mintlify-docs pull request #2
Opened 2023-11-08 12:33 UTC by hismethod

- Javascript SDK Docs를 작성했습니다.
- mint.json에는 포함시키지 않아 직접 링크로 접근하지 않는 이상 노출되지 않습니다.

2023-11-08 15:44 UTC, lukasjhan requested changes
Is it a draft? If so, change it to draft plz.

There are few things to do to finish this pr.
1. Add nav in mint.json
2. Add en version of docs.
3. Add nav in overview page both ko, en version

2023-11-08 15:44 UTC, lukasjhan commented on mint.json
> -      "pages": ["quickstart"],
Why do you change this? don't change it. What is your prettier setting?

2023-11-08 15:44 UTC, lukasjhan commented on mint.json
> +}
check the last enter char plz

2023-11-08 15:44 UTC, lukasjhan commented on mint.json
> +      "pages": [
Did you add the nav in mint.json?

2023-11-08 15:44 UTC, lukasjhan commented on sdks/overview.mdx
> +title: "Overview"
same here too

2023-11-08 15:44 UTC, lukasjhan commented on sdks/overview.mdx
> +  </Card> */}
plz don't use comments

2023-11-25 04:08 UTC, lukasjhan requested changes
Check my comments plz

2023-12-04 16:42 UTC, hismethod commented
- 상단 Sdks 를 Furo JS로 변경
- 기존 Sdks 폴더의 내용을 draft/Sdks로 이동
- Furo JS Basic Usage, Guide 항목 추가
- RN, Flutter Docs 를 Furo JS 하위 Others Platform 으로 표기

2023-12-05 04:46 UTC, lukasjhan reviewed
Ok I think it's good :) Just add en version plz

2023-12-11 06:33 UTC, hismethod commented
- Add Svelte Sample Project into Getting Started Page

2023-12-11 09:23 UTC, hismethod commented
- Added English Version Docs

2023-12-11 16:27 UTC, hismethod commented
- Furo JS en 버전의 잘못된 링크를 수정했습니다.
- Furo JS Setup 페이지에서 초기화단계에서 event 트리거 설명을 추가했습니다.
- furo.open() 에 사용되는 `appearance` params에서 제거하기로 논의한 `type` 속성에 대한 설명을 제거하였습니다.

2024-01-05 04:23 UTC, hismethod commented
- FuroJS Getting started: 페이지내 샘플 프로젝트 리스트를 카드UI로 변경
- 기존 React SDK를 Others Platform 메뉴에 항목추가 (기존사용자를 위함)

2024-01-05 04:28 UTC, lukasjhan approved these changes
Good!

2024-01-05 07:07 UTC, merged